#!/usr/bin/env python3
"""
Appendix D — Domain reconstruction and feature selectivity figures.

Reads precomputed results from output/domain_concept_analysis.json
(generated by scripts/section43/universal_concepts.py on a GPU worker)
and produces paper-quality figures. No GPU or SAE imports required.

Usage:
    python scripts/paper/appendix_d/fig_domain_reconstruction.py
"""

import json
import sys
from pathlib import Path
from typing import Dict

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

from scripts._project_root import PROJECT_ROOT
DATA_PATH = PROJECT_ROOT / "output" / "domain_concept_analysis.json"
OUTPUT_DIR = PROJECT_ROOT / "output" / "paper_figures" / "appendix_d"

# ---------------------------------------------------------------------------
# Plotting constants
# ---------------------------------------------------------------------------

# Architecture clusters, then by descending full-scale R²
MODEL_ORDER = [
    # Transformers (ICL)
    "Mitra", "TabPFN", "TabICL", "TabDPT",
    # Non-transformers
    "CARTE", "HyperFast", "Tabula-8B",
]

DOMAIN_COLORS = {
    "Business & Marketing": "#1b9e77",
    "Finance & Insurance": "#d95f02",
    "Science & Materials": "#7570b3",
    "Healthcare & Life Sciences": "#e7298a",
    "Engineering & Industry": "#66a61e",
    "Technology & Security": "#e6ab02",
}

DOMAIN_MARKERS = {
    "Business & Marketing": "o",
    "Finance & Insurance": "s",
    "Science & Materials": "^",
    "Healthcare & Life Sciences": "D",
    "Engineering & Industry": "v",
    "Technology & Security": "P",
}

DOMAIN_SHORT = {
    "Business & Marketing": "Business",
    "Finance & Insurance": "Finance",
    "Science & Materials": "Science",
    "Healthcare & Life Sciences": "Healthcare",
    "Engineering & Industry": "Engineering",
    "Technology & Security": "Technology",
}


def _save_fig(fig, output_path: Path):
    """Save figure as PDF + PNG."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(str(output_path), dpi=300, bbox_inches='tight')
    print(f"Saved: {output_path}")
    fig.savefig(str(output_path.with_suffix('.png')), dpi=300, bbox_inches='tight')
    print(f"Saved: {output_path.with_suffix('.png')}")
    plt.close(fig)


# ---------------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------------

def make_reconstruction_figure(
    all_fve: Dict[str, Dict[str, Dict[str, float]]],
    output_path: Path,
):
    """Domain reconstruction FVE vs Matryoshka scale, faceted by model."""
    domains = sorted(
        d for d in DOMAIN_COLORS
        if any(d in model_fve for model_fve in all_fve.values())
    )

    models = [m for m in MODEL_ORDER if m in all_fve]
    n_models = len(models)

    ncols = 4
    nrows = (n_models + ncols - 1) // ncols
    fig, axes = plt.subplots(nrows, ncols, figsize=(12, 3 * nrows), sharey=True)
    axes = np.atleast_2d(axes).flatten()

    for mi, model_name in enumerate(models):
        ax = axes[mi]
        model_fve = all_fve[model_name]

        # Derive scales from data keys (JSON keys are strings)
        first_domain = next(iter(model_fve.values()))
        scales = sorted(int(s) for s in first_domain.keys())
        scale_labels = [str(s) for s in scales]

        for domain in domains:
            if domain not in model_fve:
                continue
            vals = [model_fve[domain].get(str(s), np.nan) for s in scales]
            if any(np.isnan(v) for v in vals):
                continue

            short = DOMAIN_SHORT.get(domain, domain)
            color = DOMAIN_COLORS[domain]
            marker = DOMAIN_MARKERS.get(domain, "o")
            ax.plot(range(len(scales)), vals, marker=marker, linestyle='-',
                    color=color, label=short,
                    markersize=4, linewidth=1.2, zorder=3)

        ax.set_title(model_name, fontsize=9, fontweight='bold')
        ax.set_ylim(0.80, 1.005)
        ax.yaxis.grid(True, linewidth=0.3, color='#cccccc', zorder=0)
        ax.spines['top'].set_visible(False)
        ax.spines['right'].set_visible(False)
        ax.tick_params(labelsize=7)
        ax.set_xticks(range(len(scales)))
        ax.set_xticklabels(scale_labels, fontsize=6, rotation=45)

        if mi % ncols == 0:
            ax.set_ylabel('Fraction of variance explained', fontsize=8)

    for mi in range(n_models, len(axes)):
        axes[mi].axis('off')

    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, fontsize=7, loc='upper center',
               bbox_to_anchor=(0.5, 1.0), ncol=len(domains), frameon=False)

    fig.text(0.5, -0.02, 'Matryoshka cumulative scale', ha='center', fontsize=10)
    fig.tight_layout()
    fig.subplots_adjust(top=0.92)
    _save_fig(fig, output_path)


def make_selectivity_figure(
    all_selectivity: Dict[str, Dict[str, Dict[str, int]]],
    output_path: Path,
):
    """Feature selectivity stacked bars, one per model."""
    fig, ax = plt.subplots(figsize=(5.5, 4))

    models = [m for m in MODEL_ORDER if m in all_selectivity]
    n_models = len(models)

    universal_counts = []
    cluster_counts = []
    specific_counts = []
    for m in models:
        u = c = s = 0
        for band_data in all_selectivity[m].values():
            u += band_data["universal"]
            c += band_data["domain_cluster"]
            s += band_data["domain_specific"]
        universal_counts.append(u)
        cluster_counts.append(c)
        specific_counts.append(s)

    x = np.arange(n_models)
    width = 0.6

    ax.bar(x, universal_counts, width, label='Universal (all 6 domains)',
           color='#2c7bb6', zorder=3)
    ax.bar(x, cluster_counts, width, bottom=universal_counts,
           label='Domain-cluster (2\u20135)', color='#abd9e9', zorder=3)
    bottoms = [u + c for u, c in zip(universal_counts, cluster_counts)]
    ax.bar(x, specific_counts, width, bottom=bottoms,
           label='Domain-specific (0\u20131)', color='#fdae61', zorder=3)

    for i in range(n_models):
        total = universal_counts[i] + cluster_counts[i] + specific_counts[i]
        if total > 0:
            pct = 100 * universal_counts[i] / total
            ax.text(i, total + 15, f'{pct:.0f}%', ha='center', va='bottom',
                    fontsize=7, color='#2c7bb6')

    ax.set_xticks(x)
    ax.set_xticklabels(models, fontsize=8, rotation=25, ha='right')
    ax.set_ylabel('Alive SAE features', fontsize=10)
    ax.legend(fontsize=7, loc='upper left', framealpha=0.9)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    ax.tick_params(labelsize=8)

    fig.tight_layout()
    _save_fig(fig, output_path)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    if not DATA_PATH.exists():
        print(f"Error: {DATA_PATH} not found.")
        print("Run scripts/section43/universal_concepts.py on a GPU worker first.")
        sys.exit(1)

    with open(DATA_PATH) as f:
        data = json.load(f)

    meta = data["metadata"]
    print(f"Loaded: {meta['n_models']} models, {meta['n_domains']} domains")
    print(f"Data source: {meta.get('data_source', 'unknown')}")

    make_reconstruction_figure(
        data["reconstruction_r2"],
        OUTPUT_DIR / "domain_reconstruction.pdf",
    )
    make_selectivity_figure(
        data["feature_selectivity"],
        OUTPUT_DIR / "feature_selectivity.pdf",
    )

    # Print summary
    if "domain_taxonomy" in data:
        print("\nTaxonomy agreement:")
        for m in MODEL_ORDER:
            if m in data["domain_taxonomy"]:
                t = data["domain_taxonomy"][m]
                print(f"  {m}: ARI={t['ari']:.3f}, NMI={t['nmi']:.3f}")


if __name__ == '__main__':
    main()
